name: blackpink_music
description: BLACKPINK MUSIC

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1
  http: ^0.13.5
  go_router: ^6.0.1
  just_audio: ^0.9.31
  google_fonts: ^3.0.1
  collection: ^1.16.0
  logger: ^1.1.0
  lottie: ^2.2.0
  freezed_annotation: ^2.2.0
  intl: ^0.18.0
  audio_video_progress_bar: ^0.11.0
  audio_service: ^0.18.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  riverpod_generator: ^1.1.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  freezed: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/songs/
    - assets/images/
    - assets/lotties/
